### ISSUE TITLE
Errors: Uncaught Error: Extension context invalidated.

### ISSUE THREAD

**Issue by quyet4v** [J2TeamNNL/gaixinhchonloc#3]
Xin chào các bác,
Em có tiến hành cài addon này lên chrome, tuy nhiên lại có báo lỗi, nhờ các bác hỗ trợ:
![image](https://user-images.githubusercontent.com/46767711/96072950-9d98fb80-0ecf-11eb-8a1e-3991e9c9fdf5.png)
![image](https://user-images.githubusercontent.com/46767711/96072921-8eb24900-0ecf-11eb-802a-8c395172f8a5.png)
Cám ơn các bác.

**Comment by J2TeamNNL** [comment]
Bạn thử tải lại trang xem, và bạn đang dùng Facebook phiên bản mới hay cũ?

**Comment by quyet4v** [comment]
> 
> 
> Bạn thử tải lại trang xem, và bạn đang dùng Facebook phiên bản mới hay cũ?

- E dùng fb giao diện mới (chế độ nền tối).
- Load extension theo mặc định (để mặc định, k chỉnh config)
- Xóa đi cài lại đã load đc extension, k bị lỗi như trên nhưng chưa replace ads
- Bác có thể cho e xin lại link hd trong group để xem lại k ạ, để so xem e cài có thiếu bước nào k?

**Comment by J2TeamNNL** [comment]
À khi mở ra mặc định là có bật chế độ thay thế quảng cáo rồi. 

Bạn có thể inbox mình bên [Facebook]( https://fb.me/j2teamnnl) chiều mai để mình Teamview xem lỗi chứ?

**Comment by quyet4v** [comment]
Vâng, chiều mai e sẽ pm qua fb nhờ bác hỗ trợ.
Cám ơn bác.
