### ISSUE TITLE
Không thể truy cập trang web này

### ISSUE THREAD

**Issue by SocolaDaiCa** [J2TeamNNL/gaixinhchonloc#6]
![image](https://user-images.githubusercontent.com/18243451/133910119-de7c71c0-cfae-4ab4-9974-a7278f55c68b.png)

**Comment by J2TeamNNL** [comment]
ơ ông báo tôi mới để ý đấy, để tôi làm việc lại với bên bọn hosting, khó chịu quá

**Comment by SocolaDaiCa** [comment]
https://gxcl.info/ cũng thế, nên extension k chạy đc

**Comment by J2TeamNNL** [comment]
cái info tôi tạm bỏ r, tiện ích bỏ r mà 
còn web thì lên r đó
